export default function Privacy() {
  return (
    <div style={{
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      maxWidth: '800px',
      margin: '0 auto',
      padding: '40px 20px',
      lineHeight: '1.6',
      color: 'var(--foreground)',
    }}>
      <h1 style={{
        fontSize: '36px',
        marginBottom: '8px',
        color: 'var(--foreground)',
        fontWeight: '700'
      }}>
        Privacy Policy
      </h1>

      <p style={{
        fontSize: '16px',
        color: 'var(--foreground)',
        marginBottom: '40px',
        fontStyle: 'italic'
      }}>
        Last updated: 26 September 2025
      </p>

      <div style={{
        background: 'var(--background)',
        border: '1px solid var(--border)',
        borderRadius: '8px',
        padding: '24px',
        marginBottom: '32px'
      }}>
        <h2 style={{
          fontSize: '20px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600'
        }}>
          1. Introduction
        </h2>
        <p style={{ marginBottom: '16px' }}>
          Elora ("the App", "we", "our", "us") is a voice-first, emotionally intelligent journaling app. We are committed to protecting your privacy and ensuring your personal data is handled responsibly.
        </p>
        <p style={{ marginBottom: '16px' }}>
          <strong>Data Controller:</strong> Samuel McCarthy<br/>
          <strong>Contact Email:</strong> <a href="mailto:samrmccarthy6@gmail.com" style={{ color: '#007bff', textDecoration: 'none' }}>samrmccarthy6@gmail.com</a>
        </p>
        <p style={{ margin: 0 }}>
          This Privacy Policy explains what information we collect, how we use it, and the rights you have. If you do not agree with this Policy, please do not use the App.
        </p>
      </div>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid #e9ecef',
          paddingBottom: '8px'
        }}>
          2. Information We Collect
        </h2>
        <p style={{ marginBottom: '16px' }}>
          We collect the following categories of information:
        </p>
        <ul style={{ marginBottom: '16px', paddingLeft: '24px' }}>
          <li style={{ marginBottom: '12px' }}>
            <strong>Voice Recordings</strong> – spoken journal entries, processed for transcription and analysis, then deleted from our servers shortly after processing.
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>Text Entries</strong> – typed journal entries, stored locally and synced when online.
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>AI Summaries & Insights</strong> – summaries, themes, and prompts generated by Anthropic's Claude and OpenAI's GPT-4.1 Mini.
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>Embeddings</strong> – AI vector representations of summaries stored in PostgreSQL (pgvector). Embeddings are mathematical representations and cannot be reversed to recreate the original text.
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>Metadata</strong> – timestamps, device type, app version, and limited technical logs for debugging.
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>Account Data</strong> – if you choose to sign up, we collect your email address and authentication tokens via Supabase Auth (email/password or OAuth).
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>App Usage Data</strong> – aggregated feature-use metrics to help improve the user experience (only if enabled; no advertising identifiers).
          </li>
        </ul>
        <div style={{
          background: 'var(--background)',
          border: '1px solid var(--border)',
          borderRadius: '6px',
          padding: '16px',
          marginTop: '16px'
        }}>
          <p style={{ margin: 0, color: 'var(--foreground)' }}>
            <strong>We do not collect</strong> precise location, contact lists, or advertising IDs. We do not show ads.
          </p>
        </div>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid #e9ecef',
          paddingBottom: '8px'
        }}>
          3. How We Use Your Information
        </h2>
        <p style={{ marginBottom: '16px' }}>
          We use your data only to provide and improve Elora, including:
        </p>
        <ul style={{ marginBottom: '16px', paddingLeft: '24px' }}>
          <li style={{ marginBottom: '8px' }}>Enabling journaling via text and voice</li>
          <li style={{ marginBottom: '8px' }}>Providing AI-generated summaries, themes, and insights</li>
          <li style={{ marginBottom: '8px' }}>Creating your personal graph visualization ("Soul Map")</li>
          <li style={{ marginBottom: '8px' }}>Storing entries securely and syncing across devices</li>
          <li style={{ marginBottom: '8px' }}>Running background analysis jobs (e.g., profile regeneration based on journaling volume)</li>
          <li style={{ marginBottom: '8px' }}>Managing authentication and account security</li>
          <li style={{ marginBottom: '8px' }}>Improving functionality, reliability, and fixing issues</li>
        </ul>
        <p style={{
          background: 'var(--background)',
          border: '1px solid var(--border)',
          borderRadius: '6px',
          padding: '12px',
          color: 'var(--foreground)',
          margin: 0
        }}>
          <strong>We do not sell your data or share it for advertising.</strong>
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          4. Data Storage and Processing
        </h2>
        <div style={{
          display: 'grid',
          gap: '16px',
          marginBottom: '16px'
        }}>
          <div style={{
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px'
          }}>
            <h3 style={{
              fontSize: '18px',
              marginBottom: '8px',
              color: 'var(--foreground)',
              fontWeight: '600'
            }}>
              Local (Offline-First)
            </h3>
            <p style={{ margin: 0, color: 'var(--foreground)' }}>
              Entries are first saved locally on your device using expo-sqlite, so you can journal offline.
            </p>
          </div>
          <div style={{
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px'
          }}>
            <h3 style={{
              fontSize: '18px',
              marginBottom: '8px',
              color: 'var(--foreground)',
              fontWeight: '600'
            }}>
              Cloud Sync
            </h3>
            <p style={{ margin: 0, color: 'var(--foreground)' }}>
              When online, entries/summaries/embeddings sync to a PostgreSQL database hosted on Railway.
            </p>
          </div>
          <div style={{
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px'
          }}>
            <h3 style={{
              fontSize: '18px',
              marginBottom: '8px',
              color: 'var(--foreground)',
              fontWeight: '600'
            }}>
              Queueing & Authentication
            </h3>
            <p style={{ margin: 0, color: 'var(--foreground)' }}>
              Redis schedules summarization and analysis jobs. Authentication managed by Supabase Auth.
            </p>
          </div>
        </div>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          5. Third-Party Services (Processors)
        </h2>
        <p style={{ marginBottom: '16px' }}>
          To deliver AI-powered journaling, we securely transmit data to trusted processors:
        </p>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
          gap: '16px',
          marginBottom: '16px'
        }}>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px',
            textAlign: 'center'
          }}>
            <strong>Anthropic (Claude)</strong><br/>
            <span style={{ fontSize: '14px', color: 'var(--foreground)' }}>Summarization & emotional theme extraction</span>
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px',
            textAlign: 'center'
          }}>
            <strong>OpenAI (GPT-4.1 Mini)</strong><br/>
            <span style={{ fontSize: '14px', color: 'var(--foreground)' }}>Prompts, contextual insights & reflection suggestions</span>
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px',
            textAlign: 'center'
          }}>
            <strong>Supabase</strong><br/>
            <span style={{ fontSize: '14px', color: 'var(--foreground)' }}>User authentication & session management</span>
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px',
            textAlign: 'center'
          }}>
            <strong>Railway</strong><br/>
            <span style={{ fontSize: '14px', color: 'var(--foreground)' }}>Managed hosting for backend database & infrastructure</span>
          </div>
        </div>
        <div style={{
          background: 'var(--background)',
          border: '1px solid var(--border)',
          borderRadius: '6px',
          padding: '16px'
        }}>
          <p style={{ margin: 0 }}>
            When you submit a journal entry, the content (text or transcribed voice) may be transmitted securely to Anthropic and/or OpenAI solely to generate summaries, insights, or prompts. These providers may retain requests and outputs temporarily for safety/abuse monitoring and operational reliability, but <strong>do not use your data to train their models</strong> when accessed via their APIs. We do not permit any processor to use your data for advertising.
          </p>
        </div>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          6. AI Model Training
        </h2>
        <div style={{
          background: 'var(--background)',
          border: '1px solid var(--border)',
          borderRadius: '6px',
          padding: '16px'
        }}>
          <p style={{ margin: 0, color: 'var(--foreground)' }}>
            <strong>Your entries, summaries, and embeddings are not used to train Anthropic, OpenAI, or any external AI models.</strong> Processing is limited to providing the App's features back to you.
          </p>
        </div>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          7. Data Retention
        </h2>
        <ul style={{ paddingLeft: '24px' }}>
          <li style={{ marginBottom: '12px' }}>
            <strong>Voice Recordings:</strong> processed for transcription and deleted from our servers shortly after processing.
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>Text Entries, Summaries, Embeddings:</strong> retained until you delete the content or delete your account.
          </li>
          <li style={{ marginBottom: '12px' }}>
            <strong>Metadata & Technical Logs:</strong> retained for a limited period necessary for debugging, security, abuse prevention, and service reliability.
          </li>
        </ul>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          8. Your Rights (GDPR / CCPA / Australia Privacy Act)
        </h2>
        <p style={{ marginBottom: '16px' }}>
          Depending on your location, you may have the right to:
        </p>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
          gap: '12px',
          marginBottom: '16px'
        }}>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Access</strong> your personal data
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Correct</strong> inaccurate data
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Delete</strong> your data ("Right to be Forgotten")
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Restrict or Object</strong> to certain processing
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Data Portability</strong> – request an export in a portable format (e.g., JSON)
          </div>
        </div>
        <p>
          To exercise these rights, email <a href="mailto:samrmccarthy6@gmail.com" style={{ color: '#007bff', textDecoration: 'none' }}>samrmccarthy6@gmail.com</a>. We will verify your identity and respond within applicable legal timeframes.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          9. Delete My Account (Apple Requirement)
        </h2>
        <p style={{ marginBottom: '16px' }}>
          You can delete your account and associated data at any time:
        </p>
        <div style={{
          display: 'flex',
          gap: '16px',
          marginBottom: '16px',
          flexWrap: 'wrap'
        }}>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px',
            flex: '1',
            minWidth: '200px'
          }}>
            <strong>In-App:</strong> Settings → Delete Account
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '16px',
            flex: '1',
            minWidth: '200px'
          }}>
            <strong>Email:</strong> <a href="mailto:samrmccarthy6@gmail.com" style={{ color: '#856404', textDecoration: 'none' }}>samrmccarthy6@gmail.com</a> with subject "Delete My Account"
          </div>
        </div>
        <p>
          Upon deletion, your journal entries, summaries, embeddings, and personal data are permanently removed from our systems within up to 30 days (subject to limited delays from backups and processor queues). Some minimal records may be retained where legally required (e.g., fraud prevention, safety logs) and are then securely deleted.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          10. International Data Transfers
        </h2>
        <p>
          Your data may be processed in or transferred to countries outside your own (including the United States and the European Union). Where required, we rely on safeguards such as Standard Contractual Clauses (SCCs) embedded in our processors' terms to ensure an adequate level of protection.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          11. Security
        </h2>
        <p>
          We employ industry-standard technical and organizational measures, including TLS (HTTPS) in transit and encryption at rest where applicable (e.g., in PostgreSQL). Despite these measures, no method of transmission or storage is completely secure; you use the App at your own risk.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          12. Legal Bases for Processing (GDPR)
        </h2>
        <p style={{ marginBottom: '16px' }}>
          For users in the EEA/UK, we rely on the following legal bases:
        </p>
        <div style={{
          display: 'grid',
          gap: '12px',
          marginBottom: '16px'
        }}>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Consent</strong> – when you submit entries or enable AI features
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Contract</strong> – to provide the App's core services you request
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Legitimate Interests</strong> – improving reliability, security, and functionality
          </div>
          <div style={{
            background: 'var(--background)',
            border: '1px solid var(--border)',
            borderRadius: '6px',
            padding: '12px'
          }}>
            <strong>Legal Obligation</strong> – where we must comply with applicable laws
          </div>
        </div>
        <p>
          You may withdraw consent at any time (e.g., by disabling features or deleting content/account), but this will not affect processing already performed.
        </p>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          13. Children's Privacy
        </h2>
        <div style={{
          background: 'var(--background)',
          border: '1px solid var(--border)',
          borderRadius: '6px',
          padding: '16px'
        }}>
          <p style={{ margin: 0, color: 'var(--foreground)' }}>
            <strong>Elora is not intended for children under 16.</strong> We do not knowingly collect data from children. If you believe a child has provided personal data, contact us and we will delete it promptly.
          </p>
        </div>
      </section>

      <section style={{ marginBottom: '32px' }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600',
          borderBottom: '2px solid var(--border)',
          paddingBottom: '8px'
        }}>
          14. Changes to This Privacy Policy
        </h2>
        <p>
          We may update this Policy from time to time. The "Last updated" date reflects the current version. Material changes will be communicated in-app and/or by email (if you have an account). Continued use of the App after an update constitutes acceptance of the revised Policy.
        </p>
      </section>

      <section style={{
        background: 'var(--background)',
        border: '2px solid var(--border)',
        borderRadius: '8px',
        padding: '24px',
        marginBottom: '40px'
      }}>
        <h2 style={{
          fontSize: '24px',
          marginBottom: '16px',
          color: 'var(--foreground)',
          fontWeight: '600'
        }}>
          15. Contact Us
        </h2>
        <p style={{ margin: 0, fontSize: '16px' }}>
          <strong>Data Controller:</strong> Samuel McCarthy<br/>
          <strong>Email:</strong> <a href="mailto:samrmccarthy6@gmail.com" style={{ color: 'var(--foreground)', textDecoration: 'none' }}>samrmccarthy6@gmail.com</a>
        </p>
      </section>
    </div>
  );
}